### ISSUE TITLE
装上插件后后台会报错

### ISSUE THREAD

**Issue by cinyan10** [KomoriDev/nonebot-plugin-kawaii-status#13]
报以下错误, 但貌似不影响正常使用.
登录器为拉格朗, 确认卸载后无此问题
```
06-25 04:04:45 [ERROR] nonebot | Error when running RunPostProcessors
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/__init__.py", line 335, in r
un
    get_driver().run(*args, **kwargs)
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/drivers/fastapi.py", line 18
6, in run
    uvicorn.run(
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/.pyenv/versions/3.12.4/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
  File "/home/ubuntu/.pyenv/versions/3.12.4/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/message.py", line 476, in ch
eck_and_run_matcher
    await _run_matcher(
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/message.py", line 435, in _r
un_matcher
    await _apply_run_postprocessors(
> File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/message.py", line 309, in _a
pply_run_postprocessors
    await asyncio.gather(
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/utils.py", line 236, in run_
coro_with_catch
    return await coro
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 96, in __call__
    return await run_sync(cast(Callable[..., R], self.call))(**values)
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot/utils.py", line 182, in _wrapper
    result = await loop.run_in_executor(None, partial(context.run, pfunc))
  File "/home/ubuntu/.pyenv/versions/3.12.4/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/axekz-qqbot/.venv/lib/python3.12/site-packages/nonebot_plugin_alconna/matcher.py", line 1085, in _exit_executor
    matcher.executor.context.clear()
AttributeError: 'Matcher' object has no attribute 'executor'
```

**Comment by KomoriDev** [comment]
这个报错来源于 Python v3.12.4 的改动，nb 已经修复。你可以选择等待 nb 发版（估计七月初），或者降级 Python 版本至 3.12.3 及以下（

**Comment by KomoriDev** [comment]
NoneBot v2.3.2 已经发布，这个问题应该解决了。没问题便 close 了
