### ISSUE TITLE
 导入插件报错

### ISSUE THREAD

**Issue by qllokirin** [KomoriDev/nonebot-plugin-kawaii-status#17]
安装信息
```
➜  nb python3 -V
Python 3.8.10

➜  nb  nb plugin install nonebot-plugin-kawaii-status
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting nonebot-plugin-kawaii-status
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/f6/63/0113149053d0369870063c1729a98d65be7525b4566e296a159f393a0058/nonebot_plugin_kawaii_status-0.1.5-py3-none-any.whl (3.6 MB)
     |████████████████████████████████| 3.6 MB 117 kB/s
Requirement already satisfied: pillow>=10.2.0 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-kawaii-status) (10.4.0)
Requirement already satisfied: nonebot-plugin-alconna>=0.37.0 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-kawaii-status) (0.42.4)
Requirement already satisfied: py-cpuinfo>=9.0.0 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-kawaii-status) (9.0.0)
Requirement already satisfied: psutil>=5.9.8 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-kawaii-status) (6.0.0)
Requirement already satisfied: nonebot2[fastapi]>=2.2.0 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-kawaii-status) (2.2.1)
Requirement already satisfied: arclet-alconna-tools>=0.7.2 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-alconna>=0.37.0->nonebot-plugin-kawaii-status) (0.7.6)
Requirement already satisfied: nepattern>=0.6.5 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-alconna>=0.37.0->nonebot-plugin-kawaii-status) (0.7.4)
Requirement already satisfied: arclet-alconna>=1.8.7 in /usr/local/lib/python3.8/dist-packages (from nonebot-plugin-alconna>=0.37.0->nonebot-plugin-kawaii-status) (1.8.16)
Requirement already satisfied: tomli<3.0.0,>=2.0.1; python_version < "3.11" in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2.0.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (4.12.2)
Requirement already satisfied: yarl<2.0.0,>=1.7.2 in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (1.9.4)
Requirement already satisfied: pygtrie<3.0.0,>=2.4.1 in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2.5.0)
Requirement already satisfied: loguru<1.0.0,>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.7.2)
Requirement already satisfied: pydantic!=2.5.0,!=2.5.1,<3.0.0,>=1.10.0 in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (1.10.17)
Requirement already satisfied: python-dotenv<2.0.0,>=0.21.0 in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (1.0.1)
Requirement already satisfied: uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all" in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.30.1)
Requirement already satisfied: fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all" in /usr/local/lib/python3.8/dist-packages (from nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.111.0)
Requirement already satisfied: tarina>=0.5.1 in /usr/local/lib/python3.8/dist-packages (from nepattern>=0.6.5->nonebot-plugin-alconna>=0.37.0->nonebot-plugin-kawaii-status) (0.5.4)
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.8/dist-packages (from yarl<2.0.0,>=1.7.2->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (6.0.5)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0.0,>=1.7.2->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2.8)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (8.1.7)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.14.0)
Requirement already satisfied: websockets>=10.4; extra == "standard" in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (12.0)
Requirement already satisfied: pyyaml>=5.1; extra == "standard" in /usr/lib/python3/dist-packages (from uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (5.3.1)
Requirement already satisfied: httptools>=0.5.0; extra == "standard" in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.6.1)
Requirement already satisfied: watchfiles>=0.13; extra == "standard" in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.22.0)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0; (sys_platform != "win32" and (sys_platform != "cygwin" and platform_python_implementation != "PyPy")) and extra == "standard" in /usr/local/lib/python3.8/dist-packages (from uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.19.0)
Requirement already satisfied: httpx>=0.23.0 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.24.1)
Requirement already satisfied: starlette<0.38.0,>=0.37.2 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.37.2)
Requirement already satisfied: python-multipart>=0.0.7 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.0.9)
Requirement already satisfied: orjson>=3.2.1 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (3.10.5)
Requirement already satisfied: email_validator>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2.2.0)
Requirement already satisfied: jinja2>=2.11.2 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (3.1.4)
Requirement already satisfied: ujson!=4.0.2,!=4.1.0,!=4.2.0,!=4.3.0,!=5.0.0,!=5.1.0,>=4.0.1 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (5.10.0)
Requirement already satisfied: fastapi-cli>=0.0.2 in /usr/local/lib/python3.8/dist-packages (from fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.0.4)
Requirement already satisfied: anyio>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from watchfiles>=0.13; extra == "standard"->uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (3.7.1)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx>=0.23.0->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2019.11.28)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /usr/local/lib/python3.8/dist-packages (from httpx>=0.23.0->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.17.3)
Requirement already satisfied: sniffio in /usr/local/lib/python3.8/dist-packages (from httpx>=0.23.0->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (1.3.1)
Requirement already satisfied: dnspython>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from email_validator>=2.0.0->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.8/dist-packages (from jinja2>=2.11.2->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2.1.5)
Requirement already satisfied: typer>=0.12.3 in /usr/local/lib/python3.8/dist-packages (from fastapi-cli>=0.0.2->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.12.3)
Requirement already satisfied: exceptiongroup; python_version < "3.11" in /usr/local/lib/python3.8/dist-packages (from anyio>=3.0.0->watchfiles>=0.13; extra == "standard"->uvicorn[standard]<1.0.0,>=0.20.0; extra == "quart" or extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (1.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.8/dist-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.8/dist-packages (from typer>=0.12.3->fastapi-cli>=0.0.2->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (13.7.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.8/dist-packages (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.8/dist-packages (from rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.8/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer>=0.12.3->fastapi-cli>=0.0.2->fastapi<1.0.0,>=0.93.0; extra == "fastapi" or extra == "all"->nonebot2[fastapi]>=2.2.0->nonebot-plugin-kawaii-status) (0.1.2)
Installing collected packages: nonebot-plugin-kawaii-status
Successfully installed nonebot-plugin-kawaii-status-0.1.5
➜  nb

```

启动报错信息

```

07-03 21:02:19 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"
07-03 21:02:19 [SUCCESS] nonebot | Succeeded to load plugin "nonebot-plugin-npu" from "plugins.nonebot-plugin-npu"
07-03 21:02:19 [SUCCESS] nonebot | Succeeded to load plugin "uniseg" from "nonebot_plugin_alconna.uniseg"
07-03 21:02:19 [ERROR] nonebot | Failed to import "nonebot_plugin_alconna"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_kawaii_status/__init__.py", line 8, in <module>
    require("nonebot_plugin_alconna")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 179, in require
    plugin = load_plugin(name)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 39, in load_plugin
    return manager.load_plugin(module_path)
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_alconna/__init__.py", line 45, in <module>
    from .typings import AtID as AtID
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_alconna/typings.py", line 23, in <module>
    class _Text(BasePattern[Text, str]):
  File "/usr/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.8/typing.py", line 897, in __class_getitem__
    _check_generic(cls, params)
  File "/usr/local/lib/python3.8/dist-packages/typing_extensions.py", line 2911, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} {things}"
TypeError: Too few parameters for <class 'nepattern.core.BasePattern'>; actual 2, expected at least 3
07-03 21:02:19 [ERROR] nonebot | Failed to import "nonebot_plugin_kawaii_status"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 130, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 64, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 176, in load_all_plugins
    return set(
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 177, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 142, in load_plugin
    module = importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/manager.py", line 242, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/nonebot_plugin_kawaii_status/__init__.py", line 8, in <module>
    require("nonebot_plugin_alconna")
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin/load.py", line 183, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_alconna"!
07-03 21:02:19 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_apscheduler"

```

请问是因为python3.8不兼容吗还是，我在我另外一台python3.10上安装运行成功了

**Comment by qllokirin** [comment]
似乎确实是python版本兼容的问题，我换成Python 3.10.14同样的配置就不报错了

**Comment by qllokirin** [comment]
顺便问一问有考虑把use_cmd_start也写进配置里吗，我总感觉每次都要打个 / 很麻烦

**Comment by KomoriDev** [comment]
> 似乎确实是python版本兼容的问题，我换成Python 3.10.14同样的配置就不报错了

本插件依赖最新版的 NoneBot ，而 NoneBot 只支持 3.9+

**Comment by KomoriDev** [comment]
> 顺便问一问有考虑把use_cmd_start也写进配置里吗，我总感觉每次都要打个 / 很麻烦

或许你可以在配置中将 `COMMAND_START` 中多加一个 `' '`？即：`COMMAND_START = ['/',' ']` 
这样你也不需要打 `/` ，~~我也不需要改代码~~

**Comment by qllokirin** [comment]
> > 顺便问一问有考虑把use_cmd_start也写进配置里吗，我总感觉每次都要打个 / 很麻烦
> 
> 或许你可以在配置中将 `COMMAND_START` 中多加一个 `' '`？即：`COMMAND_START = ['/',' ']` 这样你也不需要打 `/` ，~我也不需要改代码~

感谢，好好好 最方便的一集
